name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r pico.hid.service/requirements.txt
    - name: Run tests with unittest/coverage
      run: coverage run --source=${{ github.workspace }}\pico.hid.service -m unittest discover -s ${{ github.workspace }}\pico.hid.service
    - name: Generate code-coverage report
      run: coverage html
    - name: Publish code coverage report
      uses: EndBug/add-and-commit@v7
      with:
        add: 'docs/* --force'
        message: 'Add generated code-coverage'
      env:
        GITHUB_TOKEN: $

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: pico.hid.service

    - uses: actions/upload-artifact@v2
      with:
        name: hid.service
        path: pico.hid.service/dist/windows

  build-installer:
    needs: build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    # Download previously built exe
    - uses: actions/download-artifact@v2
      with:
        name: hid.service
        path: pico.hid.service/dist/windows

    - run: cat pico.hid.service/dist/windows/macropad_launcher.exe

    # Install Inno Setup with chocolatey
    - name: Inno setup download
      run: choco install --verbose --yes innosetup

    # Build .iss 
    - name: Build installer using iscc
      run: iscc.exe pico.hid.service/dist/installer.iss

    # upload created installer exe
    - uses: actions/upload-artifact@v2
      with:
        name: hid.service.installer
        path: pico.hid.service/dist/installer