name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: pico.hid.service

    - uses: actions/upload-artifact@v2
      with:
        name: hid.service
        path: pico.hid.service/dist/windows

  build-installer:
    runs-on: windows-latest
    steps:
    # Install Inno Setup with chocolatey
    - name: Inno setup download
      run: choco install --verbose --yes innosetup
    # Build .iss 
    - name: Build installer using iscc
      run: iscc.exe /pico.hid.service/dist/installer.iss